development:
  adapter: mysql2
  database: ticketservice
  username: root
  encoding: utf8
  host: localhost
  
  
test:
  adapter: mysql2
  database: webui_bookmart96
  username: root
  encoding: utf8
  password: 
  host: localhost


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webui_rails11
  username: webui_rails11
  password: h3KgVjKR
  host: mysql0.locum.ru